"""
Ticker universe and company-name → ticker lookup.
Covers S&P 500, NASDAQ 100, and high-profile names mentioned in financial news.
"""
from __future__ import annotations

# ── Ticker universe (set of valid symbols) ─────────────────────────────────────
TICKER_UNIVERSE: set[str] = {
    # Mega-cap / FAANG+
    "AAPL","MSFT","AMZN","GOOGL","GOOG","META","TSLA","NVDA","NFLX","PYPL",
    # Berkshire
    "BRK.A","BRK.B",
    # Financials
    "JPM","BAC","WFC","C","GS","MS","AXP","BLK","SCHW","USB","PNC","TFC",
    "COF","BK","STT","FITB","KEY","RF","HBAN","MTB","CFG","CMA","ZION","ALLY",
    "SYF","DFS","NDAQ","ICE","CME","CBOE","MCO","SPGI","MA","V","AFRM","SOFI",
    "COIN","HOOD","UPST","LC","OPEN","UWMC",
    # Healthcare / Pharma / Biotech
    "JNJ","UNH","PFE","ABBV","MRK","LLY","BMY","AMGN","GILD","REGN","VRTX",
    "BIIB","MRNA","BNTX","ZTS","ISRG","SYK","BSX","EW","MDT","BAX","BDX",
    "DHR","TMO","IQV","A","PKI","HOLX","DXCM","PODD","AMED","HUM","CVS","CI",
    "MCK","CAH","ABC","ANTM","CNC","MOH","WBA","RAD","PRGO","ENDP","JAZZ",
    # Technology
    "INTC","AMD","QCOM","AVGO","TXN","MU","AMAT","LRCX","KLAC","MCHP","ADI",
    "ON","SWKS","QRVO","MPWR","ENPH","SEDG","SLAB","MKSI","COHU","WOLF",
    "CRM","NOW","INTU","ADBE","ORCL","SAP","SNOW","PLTR","DDOG","ZS","CRWD",
    "PANW","FTNT","NET","OKTA","TENB","RPM","VRNS","CYBR","S","ESTC","SPLK",
    "IBM","HPE","HPQ","DELL","NTAP","STX","WDC","PURE","PSTG","EMC",
    "CSCO","FFIV","JNPR","ANET","CIEN","LITE","VIAV","INFN","CGNX",
    "MSCI","AKAM","TWLO","BAND","RNG","EGHT","FIVN","NICE","ALRM","NEWR",
    "AMZN","SHOP","ETSY","EBAY","W","CHWY","WISH","OVRLY","SE","MELI","GRAB",
    "UBER","LYFT","DASH","ABNB","AIRB","BKNG","EXPE","TRIP","YELP",
    "GOOGL","SNAP","PINS","TWTR","RDDT","MTCH","BMBL","ZM","DOCU","BOX","DBX",
    "RBLX","UNITY","EA","TTWO","ATVI","GME","AMC","PTON","PELOTON",
    "ROKU","FUBO","PLEX","PARA","WBD","DIS","CMCSA","CHTR","FOXA","FOX",
    "SPOT","SIRI","IDXX","IRDM","MAXR",
    # Energy
    "XOM","CVX","COP","SLB","HAL","BKR","EOG","PXD","DVN","FANG","MPC",
    "VLO","PSX","HES","APA","OXY","MRO","NOV","RIG","VAL","NE","DO",
    "WMB","KMI","OKE","ET","EPD","MPLX","PAA","HEP","DCP","TRGP","AM",
    # Consumer / Retail
    "WMT","COST","TGT","HD","LOW","AZO","ORLY","AAP","KR","SWY","PFGC",
    "MCD","SBUX","CMG","YUM","QSR","JACK","DRI","EAT","CAKE","TXRH",
    "NKE","UAA","UA","PVH","VFC","HBI","RL","TPR","CPRI","KORS","TJX",
    "ROST","BURL","GPS","ANF","AEO","URBN","CHS","CHICO","PVH",
    "KO","PEP","MDLZ","GIS","K","CPB","HRL","SJM","CAG","MKC","CHD",
    "CLX","CL","PG","EL","ULTA","COTY","REV","ESTE","ENR","SPB","PC",
    "PM","MO","BTI","RAI","IMBBY","VGR",
    # Industrials
    "GE","HON","MMM","ETN","EMR","ROK","PH","ITW","IR","AME","CARR","OTIS",
    "TDG","HII","NOC","LMT","RTX","BA","GD","L3H","TDY","HXL","AXON",
    "DE","CAT","PCAR","CMI","TEX","AGCO","CNHI","WAB","TRN","GATX",
    "UNP","CSX","NSC","JBHT","CHRW","XPO","SAIA","ODFL","WERN","KNX",
    "FDX","UPS","AMBC","EXPD","GXO","CEVA",
    "WM","RSG","CVA","SRCL","CECO","ACI","ERII",
    "JCI","TRANE","PNR","RXO","GNRC","REXNORD","WATTS","CFX","IDEX","DCI",
    # Utilities / REITs
    "NEE","DUK","SO","D","AEP","EXC","XEL","WEC","ES","AWK","AEE","CMS",
    "PPL","LNT","EVRG","PNW","OGE","NI","POR","SRE","PCG","EIX","ED",
    "AMT","PLD","CCI","EQIX","DLR","SBAC","IRM","PSA","EXR","CUBE","LSI",
    "SPG","MAC","CBL","WPG","SKT","BPR","BRX","KIM","REG","FRT","NNN",
    "O","STAG","EFC","AGNC","NLY","MFA","PMT","TWO","IVR","CIM","RWT",
    # Healthcare REITs
    "WELL","VTR","PEAK","OHI","NHI","SNH","HR","CHCT","GMRE","LTC",
    # Materials
    "LIN","APD","ALB","SHW","PPG","RPM","ECL","IFF","EMN","HUN","CC",
    "NEM","AEM","GOLD","KGC","AU","AGI","WPM","PAAS","SVM","HL","CDE",
    "FCX","SCCO","HBM","TECK","AA","CENX","KALU","ARNC","ATI","CMC",
    "NUE","STLD","CLF","AK","MT","X","WOR","ZEUS","RS","OSS",
    # Communication
    "VZ","T","TMUS","LUMN","SHEN","ATUS","LBTYB","LBTYA","CHTR","CABO",
    # ETFs / Macro tickers (commonly mentioned)
    "SPY","QQQ","DIA","IWM","VTI","GLD","SLV","USO","TLT","HYG","LQD",
    "XLF","XLK","XLV","XLE","XLU","XLI","XLP","XLY","XLRE","XLC",
    "ARKK","ARKG","ARKW","ARKQ","ARKF","ARKX",
    "SOXL","SOXS","TQQQ","UPRO","SPXL","SPXS","UVXY","VIX",
    # Crypto-adjacent
    "MSTR","MARA","RIOT","HUT","CIFR","BTBT","BITO","ETHE","GBTC",
    # Auto
    "F","GM","STLA","TM","HMC","NSANY","VWAGY","BMWYY","MBGYY",
    "TSLA","RIVN","LCID","FSR","GOEV","NKLA","WKHS","IDEANOMICS","SOLO",
    # Chinese ADRs
    "BABA","JD","PDD","BIDU","NIO","XPEV","LI","TME","IQ","BILI","EDU",
    "TAL","DIDI","LAIX","ZH","VNET","GDS","CANG","AGORA",
    # Misc high-profile
    "TWLO","ASAN","MDB","GTLB","DDOG","CFLT","MNDY","U","PATH","APPN",
    "ZEN","FROG","SUMO","DT","PD","OPSF","PCOR","AVLR","COUP","NCNO",
    "HUBS","FRSH","AI","BBAI","SOUN","ITRN","LPSN","BRZE","IOT",
    "AYX","ALTERYX","CLDR","CDK","PRGS","MANH","NCNO","JAMF","PING",
}

# Words that look like tickers but should never match
_STOPWORDS: set[str] = {
    "A","I","AN","AS","AT","BE","BY","DO","GO","HE","IF","IN","IS","IT",
    "ME","MY","NO","OF","ON","OR","SO","TO","UP","US","WE","OK",
    "ALL","AND","ARE","BUT","CAN","DID","FOR","GET","GOT","HAS","HAD",
    "HIM","HIS","HOW","ITS","LET","MAY","NEW","NOT","NOW","OFF","OLD",
    "ONE","OUR","OUT","OWN","PER","PUT","SAY","SEE","SET","THE","TOO",
    "TWO","USE","WAS","WHO","WHY","WITH","YOU",
    "ALSO","BACK","BEEN","BEST","BOTH","CALL","CAME","COME","DOES","DOWN",
    "EACH","EVEN","EVER","FIND","FIVE","FROM","FULL","GIVE","GOES","GOOD",
    "HALF","HAVE","HERE","HIGH","HOLD","HOME","INTO","JUST","KEEP","KNOW",
    "LAST","LATE","LEAD","LEFT","LIKE","LIVE","LONG","LOOK","LOSS","MADE",
    "MAKE","MANY","MARK","MORE","MOST","MOVE","MUCH","MUST","NEXT","ONLY",
    "OPEN","OVER","PART","PAST","PLAN","PLAY","PLUS","REAL","RISE","ROLE",
    "SAID","SAME","SELL","SHOW","SIDE","SIGN","SOLD","SOME","SOON","STAY",
    "SUCH","TAKE","THAN","THAT","THEM","THEN","THEY","THIS","THUS","TIME",
    "TOLD","TOOK","TURN","UNIT","UPON","USED","WELL","WENT","WERE","WHAT",
    "WHEN","WILL","WISH","YEAR","ZERO","DEAL","FUND","FIRM","BANK","RATE",
    "LOSS","GAIN","RISE","FALL","HIGH","LOW","NET","CEO","CFO","COO","CTO",
    "AI","ML","EV","AR","VR","IPO","ETF","GDP","CPI","FED","SEC","FDA","NYSE","NASDAQ","DOW","S&P",
    "EBIT","GAAP","DEBT","CASH","BOND","NOTE","YIELD","TRADE","SHARE",
    "PRICE","STOCK","MARKET","INDEX","FUND","TRUST","CORP","INC","LLC",
    "LTD","PLC","AG","SA","SE","NV","BV","KK","CO","GROUP","HOLDINGS",
}

# ── Company name → ticker lookup ───────────────────────────────────────────────
COMPANY_TO_TICKER: dict[str, str] = {
    # Big tech
    "apple":            "AAPL",
    "microsoft":        "MSFT",
    "amazon":           "AMZN",
    "alphabet":         "GOOGL",
    "google":           "GOOGL",
    "meta":             "META",
    "facebook":         "META",
    "tesla":            "TSLA",
    "nvidia":           "NVDA",
    "netflix":          "NFLX",
    "paypal":           "PYPL",
    # Financials
    "jpmorgan":         "JPM",
    "jp morgan":        "JPM",
    "bank of america":  "BAC",
    "wells fargo":      "WFC",
    "citigroup":        "C",
    "citi":             "C",
    "goldman sachs":    "GS",
    "morgan stanley":   "MS",
    "american express": "AXP",
    "blackrock":        "BLK",
    "charles schwab":   "SCHW",
    "visa":             "V",
    "mastercard":       "MA",
    "coinbase":         "COIN",
    # Healthcare
    "johnson & johnson":"JNJ",
    "johnson and johnson":"JNJ",
    "unitedhealth":     "UNH",
    "pfizer":           "PFE",
    "abbvie":           "ABBV",
    "merck":            "MRK",
    "eli lilly":        "LLY",
    "lilly":            "LLY",
    "bristol myers":    "BMY",
    "bristol-myers":    "BMY",
    "amgen":            "AMGN",
    "gilead":           "GILD",
    "moderna":          "MRNA",
    "biontech":         "BNTX",
    "regeneron":        "REGN",
    "vertex":           "VRTX",
    "biogen":           "BIIB",
    # Retail / Consumer
    "walmart":          "WMT",
    "costco":           "COST",
    "target corp":      "TGT",
    "target corporation": "TGT",
    "home depot":       "HD",
    "lowe's":           "LOW",
    "lowes":            "LOW",
    "mcdonald's":       "MCD",
    "mcdonalds":        "MCD",
    "starbucks":        "SBUX",
    "chipotle":         "CMG",
    "nike":             "NKE",
    "coca-cola":        "KO",
    "coca cola":        "KO",
    "pepsi":            "PEP",
    "pepsico":          "PEP",
    "procter & gamble": "PG",
    "procter and gamble":"PG",
    # Energy
    "exxon":            "XOM",
    "exxonmobil":       "XOM",
    "chevron":          "CVX",
    "conocophillips":   "COP",
    "schlumberger":     "SLB",
    "halliburton":      "HAL",
    # Industrials
    "general electric": "GE",
    "honeywell":        "HON",
    "3m":               "MMM",
    "boeing":           "BA",
    "lockheed":         "LMT",
    "lockheed martin":  "LMT",
    "northrop":         "NOC",
    "northrop grumman": "NOC",
    "raytheon":         "RTX",
    "fedex":            "FDX",
    "ups":              "UPS",
    "union pacific":    "UNP",
    "deere":            "DE",
    "john deere":       "DE",
    "caterpillar":      "CAT",
    # Semiconductors
    "intel":            "INTC",
    "advanced micro":   "AMD",
    "amd":              "AMD",
    "qualcomm":         "QCOM",
    "broadcom":         "AVGO",
    "texas instruments":"TXN",
    "micron":           "MU",
    "applied materials":"AMAT",
    # Communication
    "verizon":          "VZ",
    "at&t":             "T",
    "t-mobile":         "TMUS",
    "comcast":          "CMCSA",
    "disney":           "DIS",
    "warner bros":      "WBD",
    "warner brothers":  "WBD",
    "paramount":        "PARA",
    "fox":              "FOXA",
    "spotify":          "SPOT",
    "snap":             "SNAP",
    "pinterest":        "PINS",
    "twitter":          "TWTR",
    "x corp":           "TWTR",
    "reddit":           "RDDT",
    "match group":      "MTCH",
    "roblox":           "RBLX",
    "unity":            "U",
    "electronic arts":  "EA",
    "activision":       "ATVI",
    "take-two":         "TTWO",
    "gamestop":         "GME",
    "amc":              "AMC",
    # EV / Auto
    "ford":             "F",
    "general motors":   "GM",
    "rivian":           "RIVN",
    "lucid":            "LCID",
    "fisker":           "FSR",
    "nikola":           "NKLA",
    "workhorse":        "WKHS",
    # Chinese tech
    "alibaba":          "BABA",
    "jd.com":           "JD",
    "baidu":            "BIDU",
    "tencent":          "TCEHY",
    "bytedance":        "BDNCE",
    "pinduoduo":        "PDD",
    # Software / SaaS
    "salesforce":       "CRM",
    "servicenow":       "NOW",
    "intuit":           "INTU",
    "adobe":            "ADBE",
    "oracle":           "ORCL",
    "snowflake":        "SNOW",
    "palantir":         "PLTR",
    "datadog":          "DDOG",
    "zscaler":          "ZS",
    "crowdstrike":      "CRWD",
    "palo alto":        "PANW",
    "palo alto networks":"PANW",
    "fortinet":         "FTNT",
    "cloudflare":       "NET",
    "okta":             "OKTA",
    "twilio":           "TWLO",
    "zoom":             "ZM",
    "docusign":         "DOCU",
    "shopify":          "SHOP",
    "uber":             "UBER",
    "lyft":             "LYFT",
    "doordash":         "DASH",
    "airbnb":           "ABNB",
    "booking":          "BKNG",
    "expedia":          "EXPE",
    "peloton":          "PTON",
    "robinhood":        "HOOD",
    "sofi":             "SOFI",
    "affirm":           "AFRM",
    "upstart":          "UPST",
    "microstrategy":    "MSTR",
    "marathon digital": "MARA",
    "riot platforms":   "RIOT",
    # Macro / indices (mentioned in headlines)
    "s&p 500":          "SPY",
    "s&p500":           "SPY",
    "nasdaq":           "QQQ",
    "dow jones":        "DIA",
    "russell 2000":     "IWM",
}
